In [1]:
!pip3 install torch

In [0]:
import torch

In [4]:
one_d = torch.arange(0, 9) # 범위 0부터 8까지. 마지막 9는 제외.
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
two_d = one_d.view(3, 3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
two_d.dim()

2

In [9]:
two_d[0, 0] # R, C
# Row, Column

tensor(0)

In [10]:
two_d[1, 2]

tensor(5)

In [11]:
x = torch.arange(0, 18).view(2, 3, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [12]:
x1 = torch.arange(0, 18).view(3, 3, 2)
x1

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])