In [1]:
!pip3 install torch

In [0]:
import torch

In [3]:
x = torch.arange(18).view(3, 2, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [4]:
x[1, 1, 1] # 1번 행렬에서 1 Row, 1 Column 값을 뽑아라

tensor(10)

In [6]:
x[1, 1, 2] # 1번 행렬에서 1 Row, 2 Coulmn 값을 뽑아라

tensor(11)

In [7]:
x[1, 0:2, 1]

tensor([ 7, 10])

In [8]:
x[1, 0:2, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [10]:
x[1, :, :] # 1번 행렬에서 전체를 뽑아라

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])