In [1]:
from __future__ import print_function
import torch

In [2]:
# 무작위로 초기화된 행렬 생성

x = torch.empty(5, 3)
print(x)

tensor([[4.7550e+14, 3.0744e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0744e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.4005e+14]])


In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
x = torch.ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.7675,  0.2388,  0.8904],
        [-0.4574, -0.7235,  0.2455],
        [-1.3828, -0.8758, -0.8722],
        [-0.1698, -1.5441, -2.1481],
        [-0.9251, -1.5050, -0.1114]])


In [9]:
print(x.size())

torch.Size([5, 3])


### 연산 operations

In [12]:
print(x)

tensor([[-1.7675,  0.2388,  0.8904],
        [-0.4574, -0.7235,  0.2455],
        [-1.3828, -0.8758, -0.8722],
        [-0.1698, -1.5441, -2.1481],
        [-0.9251, -1.5050, -0.1114]])


In [11]:
y = torch.rand(5, 3)
print(y)

tensor([[0.3151, 0.7791, 0.4009],
        [0.0098, 0.8853, 0.5211],
        [0.5815, 0.4481, 0.0882],
        [0.4526, 0.7791, 0.4305],
        [0.4025, 0.8816, 0.0614]])


In [13]:
print(x+y)

tensor([[-1.4525,  1.0180,  1.2913],
        [-0.4476,  0.1618,  0.7666],
        [-0.8013, -0.4277, -0.7840],
        [ 0.2828, -0.7650, -1.7176],
        [-0.5226, -0.6234, -0.0500]])


In [14]:
print(torch.add(x, y))

tensor([[-1.4525,  1.0180,  1.2913],
        [-0.4476,  0.1618,  0.7666],
        [-0.8013, -0.4277, -0.7840],
        [ 0.2828, -0.7650, -1.7176],
        [-0.5226, -0.6234, -0.0500]])


In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.4525,  1.0180,  1.2913],
        [-0.4476,  0.1618,  0.7666],
        [-0.8013, -0.4277, -0.7840],
        [ 0.2828, -0.7650, -1.7176],
        [-0.5226, -0.6234, -0.0500]])


In [16]:
y.add_(x)
print(y)

tensor([[-1.4525,  1.0180,  1.2913],
        [-0.4476,  0.1618,  0.7666],
        [-0.8013, -0.4277, -0.7840],
        [ 0.2828, -0.7650, -1.7176],
        [-0.5226, -0.6234, -0.0500]])


In [19]:
print(y[:, 1])

tensor([ 1.0180,  0.1618, -0.4277, -0.7650, -0.6234])


In [20]:
# 크기 변경 - torch.view

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9612])
-0.9611868262290955


In [28]:
# Torch Tensor -> Numpy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [30]:
a.add_(1)
# add_ 덧셈해서 그걸 바로 적용해라

print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [31]:
# Numpy -> Torch Tensor
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [32]:
# CUDA Tensors

if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))