In [ ]:
# autograd : Tensor의 모든 연산에 대해 자동 미분 제공.

# 패키지의 중심에는 torch.Tensor 클래스가 있습니다. 
# 만약 .requires_grad 속성을 True 로 설정하면, 
# 그 tensor에서 이뤄진 모든 연산들을 추적(track)하기 시작합니다. 

# 계산이 완료된 후 .backward() 를 호출하여 모든 변화도(gradient)를 자동으로 계산할 수 있습니다. 
# 이 Tensor의 변화도는 .grad 속성에 누적됩니다.

In [ ]:
# Tensor가 기록을 추적하는 것을 중단하게 하려면, 
# .detach() 를 호출하여 연산 기록으로부터 분리(detach)하여 이후 연산들이 추적되는 것을 방지

In [ ]:
# 기록을 추적하는 것(과 메모리를 사용하는 것)을 방지하기 위해, 
# 코드 블럭을 with torch.no_grad(): 로 감쌀 수 있습니다. 

# 이는 특히 변화도(gradient)는 필요없지만, requires_grad=True 가 설정되어 
# 학습 가능한 매개변수를 갖는 모델을 평가(evaluate)할 때 유용합니다.

In [2]:
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [15]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [9]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [10]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [11]:
b = (a * a).sum()
print(b.grad_fn)

In [16]:
# Gradient
out.backward()
print(x.grad)

tensor([[9., 9.],
        [9., 9.]])


In [17]:
x = torch.randn(3, requires_grad=True)
y = x * 2

while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([-657.0859, -757.9207,  -81.3516], grad_fn=<MulBackward0>)


In [18]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [20]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


In [21]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
