In [1]:
!pip3 install torch

In [0]:
import torch
from torch.nn import Linear

In [3]:
torch.manual_seed(1)
model = Linear(in_features = 1, out_features = 1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [7]:
x = torch.tensor([[2.0], [3.3]])
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)
